Parameters:
  VegaExternalIdParameter:
    Type: String
    Description: Vega Cloud's ExternalId for your environments (helps to authenticate role assumption).
    Default: "vega:<get_id_from_vega_csm>"
Resources:
  VegaOptimizer:
    # This role and policy are used by the Vega Platform discover, tag resources, and optimize yoour account(s)
    # Optimize includes minimal permission for such actions as starting/stopping instances, modifying instance types
    Properties:
      RoleName: VegaOptimizer
      AssumeRolePolicyDocument:
        Statement:
          - Action: "sts:AssumeRole"
            Condition:
              StringEquals:
                "sts:ExternalId": !Ref VegaExternalIdParameter
            Effect: Allow
            Principal:
              # 955075715928 This one of the Vega Data Collection Accounts
              # 549829454055 This one of the Vega Data Collection Accounts
              # 933023916684 This is the Vega Saas Platform Account
              AWS: ["arn:aws:iam::955075715928:root", "arn:aws:iam::549829454055:root", "arn:aws:iam::933023916684:root"]
          - Action: "sts:AssumeRole"
            Effect: Allow
            Principal:
              Service: ["cloudformation.amazonaws.com"]
        Version: 2012-10-17
    Type: "AWS::IAM::Role"
  OptimizerPolicy:
    DependsOn: VegaOptimizer
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyDocument:
        Statement:
          # CloudWatch Metrics Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              - "cloudwatch:GetMetricData"
              - "cloudwatch:GetMetricStatistics"
              - "cloudwatch:ListMetrics"
              - "cloudwatch:ListTagsForResource"
          # EC2 Resource Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              - "ec2:Describe*"
              - "ec2:GetCapacityReservationUsage"
              - "ec2:GetGroupsForCapacityReservation"
              - "ec2:GetHostReservationPurchasePreview"
          # EC2 Tag Management
          - Effect: Allow
            Resource: "*"
            Action:
              - "ec2:CreateTags"
              - "ec2:DeleteTags"
          # EC2 FinOps Optimize
          - Effect: Allow
            Resource: "*"
            Action:
              - "ec2:ModifyInstanceAttribute"
              - "ec2:ModifyInstancePlacement"
              - "ec2:ModifySnapshotAttribute"
              - "ec2:ModifyVolumeAttribute"
              - "ec2:RunInstances"
              - "ec2:StartInstances"
              - "ec2:StopInstances"
              - "kms:CreateGrant"
          # RDS Resource Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              - "rds:DescribeDBClusterSnapshots"
              - "rds:DescribeDBClusters"
              - "rds:DescribeDBClusterSnapshots"
              - "rds:DescribeRecommendationGroups"
              - "rds:DescribeRecommendations"
              - "rds:DescribeReservedDBInstances"
              - "rds:DescribeReservedDBInstancesOfferings"
              - "rds:DescribeDBInstances"
              - "rds:DescribeDBSnapshots"
              - "rds:ListTagsForResource"
          # RDS Tag Management
          - Effect: Allow
            Resource: "*"
            Action:
              - "rds:AddTagsToResource"
              - "rds:RemoveTagsFromResource"
          # RDS FinOps Optimize
          - Effect: Allow
            Resource: "*"
            Action:
              - "rds:ModifyDBCluster"
              - "rds:ModifyDBClusterSnapshotAttribute"
              - "rds:ModifyDBClusterSnapshot"
              - "rds:ModifyDBInstance"
              - "rds:ModifyDBSnapshot"
              - "rds:ModifyDBSnapshotAttribute"
              - "rds:RebootDBInstance"
              - "rds:StartDBCluster"
              - "rds:StartDBInstance"
              - "rds:StopDBCluster"
              - "rds:StopDBInstance"
              - "rds:ModifyCurrentDBClusterCapacity"
          # Elastic Container Service (ECS)
          - Effect: Allow
            Resource: "*"
            Action:
              - "ecs:Describe*"
              - "ecs:List*"
          # Elastic Container Service (ECS) Tag Management
          - Effect: Allow
            Resource: "*"
            Action:
              - "ecs:TagResource"
              - "ecs:UntagResource"
          # Elastic Kubernetes Service (EKS)
          - Effect: Allow
            Resource: "*"
            Action:
              - "eks:Describe*"
              - "eks:List*"
          # Elastic Kubernetes Service (EKS) Tag Management
          - Effect: Allow
            Resource: "*"
            Action:
              - "eks:TagResource"
              - "eks:UntagResource"
          # ElastiCache Resource Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              - "elasticache:Describe*"
              - "elasticache:List*"
          # ElastiCache Tag Management
          - Effect: Allow
            Resource: "*"
            Action:
              - "elasticache:AddTagsToResource"
              - "elasticache:RemoveTagsFromResource"
          # ElastiCache FinOps Optimize
          - Effect: Allow
            Resource: "*"
            Action:
              - "elasticache:DecreaseReplicaCount"
              - "elasticache:ModifyCacheCluster"
              - "elasticache:ModifyCacheParameterGroup"
              - "elasticache:ModifyCacheSubnetGroup"
              - "elasticache:ModifyReplicationGroup"
              - "elasticache:RebootCacheCluster"
              - "elasticache:RebalanceSlotsInGlobalReplicationGroup"
          # Redshift Resource Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              - "redshift:DescribeReservedNodes"
              - "redshift:DescribeReservedNodeExchangeStatus"
              - "redshift:DescribeReservedNodeOfferings"
              - "redshift:DescribeClusters"
              - "redshift:DescribeClusterSnapshots"
              - "redshift:DescribeStorage"
              - "redshift:DescribeTags"
              - "redshift:GetReservedNodeExchangeOfferings"
              - "redshift:GetReservedNodeExchangeConfigurationOptions"
          # Redshift Tag Management
          - Effect: Allow
            Resource: "*"
            Action:
              - "redshift:CreateTags"
              - "redshift:DeleteTags"
          # Redshift FinOps Optimize
          - Effect: Allow
            Resource: "*"
            Action:
              - "redshift:PauseCluster"
              - "redshift:ResizeCluster"
              - "redshift:ResumeCluster"
          # DynamoDB Resource Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              - "dynamodb:DescribeReservedCapacity"
              - "dynamodb:DescribeReservedCapacityOfferings"
              - "dynamodb:ListTagsOfResource"
              - "dynamodb:Describe*"
              - "dynamodb:List*"
          # DynamoDB Tag Management
          - Effect: Allow
            Resource: "*"
            Action:
              - "dynamodb:TagResource"
              - "dynamodb:UntagResource"
          # DynamoDB FinOps Optimize
          - Effect: Allow
            Resource: "*"
            Action:
              - "dynamodb:PurchaseReservedCapacityOfferings"
          # Opensearch Resource Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              - "es:DescribeReservedElasticsearchInstances"
              - "es:DescribeReservedElasticsearchInstanceOfferings"
              - "es:DescribeReservedInstances"
              - "es:DescribeReservedInstanceOfferings"
              - "es:ListTags"
          # Opensearch Tag Management
          - Effect: Allow
            Resource: "*"
            Action:
              - "es:AddTags"
              - "es:RemoveTags"
          # Medialive Resource Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              - "medialive:DescribeReservation"
              - "medialive:ListReservations"
              - "medialive:ListTagsForResource"
          # Medialive Tag Management
          - Effect: Allow
            Resource: "*"
            Action:
              - "medialive:TagResource"
              - "medialive:UntagResource"
          # Trusted Advisor Resource Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              - "support:DescribeTrustedAdvisorCheckRefreshStatuses"
              - "support:DescribeTrustedAdvisorCheckResult"
              - "support:DescribeTrustedAdvisorChecks"
              - "support:DescribeTrustedAdvisorCheckSummaries"
              - "support:RefreshTrustedAdvisorCheck"
              - "trustedadvisor:Describe*"
          # Savings Plan Resource Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              - "savingsplans:*"
          # Compute Optimizer Resource Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              - "compute-optimizer:GetAutoScalingGroupRecommendations"
              - "compute-optimizer:GetEBSVolumeRecommendations"
              - "compute-optimizer:GetEC2InstanceRecommendations"
              - "compute-optimizer:GetEC2RecommendationProjectedMetrics"
              - "compute-optimizer:GetEffectiveRecommendationPreferences"
              - "compute-optimizer:GetEnrollmentStatus"
              - "compute-optimizer:GetEnrollmentStatusesForOrganization"
              - "compute-optimizer:GetLambdaFunctionRecommendations"
              - "compute-optimizer:GetRecommendationPreferences"
              - "compute-optimizer:GetRecommendationSummaries"
          # S3 Resource Discovery
          - Effect: Allow
            Resource: "*"
            Action:
              # Note: Get* is filtered with an explicit deny on GetObject below.
              - "s3:Get*"
              - "s3:List*"
          - Action:
              - "s3:GetObject"
            Effect: Deny
            Resource: "*"
          # S3 Tag Management
          - Effect: Allow
            Resource: "*"
            Action:
              - "s3:PutObjectTagging"
              - "s3:DeleteObjectTagging"
              - "s3:DeleteObjectVersionTagging"
              - "s3:PutObjectVersionTagging"
          # s3 FinOps Optimize
          - Effect: Allow
            Resource: "*"
            Action:
              - "s3:PutLifecycleConfiguration"
              - "s3:DeleteLifecycleConfiguration"
      PolicyName: VegaOptimizerPolicy
      Roles:
        - VegaOptimizer
